# Generated by Django 3.2.15 on 2022-09-18 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20220918_1539'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimpleUser',
        ),
    ]
