# Generated by Django 3.2.15 on 2022-10-05 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_delete_simpleuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField()),
                ('name', models.CharField(max_length=150)),
                ('event', models.TextField(max_length=1000)),
                ('date', models.DateTimeField()),
                ('date_placed', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
