# Generated by Django 3.2.15 on 2022-10-05 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date_placed',
        ),
    ]
