# Generated by Django 3.2.15 on 2022-10-05 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_event_date_placed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event',
            new_name='text',
        ),
    ]
