# Generated by Django 3.2.15 on 2022-10-15 09:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_rename_event_event_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_of_reg',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
